import { Link } from '@tanstack/react-router'
import { CritupLogo } from '@/components/CritupLogo'
import { useTheme, useColors } from '@/lib/theme'

const FONT = "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', 'Inter', sans-serif"

const sections = [
  {
    title: '1. About Critup.ai',
    body: `Critup.ai ("the Service", "we", "us", "our") is an AI-powered design critique platform operated by Avraam Valikhan and Adil Kamal Batcha ("the Operators"). By creating an account or using the Service you agree to these Terms in full. If you do not agree, do not use the Service.`,
  },
  {
    title: '2. Eligibility',
    body: `You must be at least 16 years old to use Critup.ai. By registering, you confirm that all information you provide is accurate and that you have the legal capacity to enter into these Terms. The Service is designed for architecture, interior design, and urban planning students but is open to all design disciplines.`,
  },
  {
    title: '3. AI-Generated Content — Important Disclaimer',
    body: `ALL feedback, scores, critique, jury questions, and coaching generated by Critup.ai is produced by artificial intelligence (Anthropic Claude API) and is provided for EDUCATIONAL AND INFORMATIONAL PURPOSES ONLY. It does not constitute professional architectural, design, or academic advice. It is not a substitute for feedback from licensed professionals, faculty, or qualified instructors.\n\nAI-generated content may be inaccurate, incomplete, inconsistent, or biased. Scores may vary between identical submissions. You accept full responsibility for how you interpret and apply any AI-generated feedback. We make no representation that any feedback will improve your academic outcomes, jury performance, or professional work.`,
  },
  {
    title: '4. Your Content and Licence',
    body: `You retain full ownership of all project files, drawings, and materials you upload. By uploading, you grant Critup.ai a limited, non-exclusive, royalty-free licence to process, store, and transmit your files solely to provide the Service to you. This licence terminates when you delete your content or close your account.\n\nYou are solely responsible for ensuring you have the right to upload any material you submit. You must not upload content that infringes intellectual property rights, contains unlawful material, or violates the rights of any third party.`,
  },
  {
    title: '5. Acceptable Use',
    body: `You may not: (a) use the Service for any unlawful purpose; (b) attempt to reverse-engineer, scrape, or systematically extract data from the Service; (c) use automated tools to submit bulk requests; (d) impersonate any person or entity; (e) attempt to gain unauthorised access to any part of the Service; (f) use the Service to train, benchmark, or improve any competing AI system. Violations may result in immediate account suspension without notice or refund.`,
  },
  {
    title: '6. Subscriptions and Payments',
    body: `Paid plans are billed in advance on a monthly or annual cycle through our payment processor (Paddle). All fees are stated in USD and are exclusive of any applicable taxes, which are your responsibility. You may cancel at any time from Settings; access continues until the end of the current billing period. We reserve the right to change pricing with 30 days' notice.`,
  },
  {
    title: '7. Refund Policy',
    body: `Monthly plans: We do not offer refunds on monthly subscriptions. You may cancel at any time and your access will continue until the end of the current billing period, after which you will not be charged again.\n\nAnnual plans: If you purchase an annual subscription and have not used the Service (i.e., have not submitted any project for analysis), you may request a full refund within 7 days of the original purchase date by emailing hello@critup.ai. Refund requests made after 7 days, or where the Service has been used, will not be eligible.\n\nProrated refunds are not available for any plan type. Refunds are processed back to the original payment method within 5–10 business days. This policy does not affect any statutory rights you may have under applicable consumer protection law.`,
  },
  {
    title: '8. Service Availability',
    body: `We aim to keep Critup.ai available but make no guarantees of uptime, continuity, or error-free operation. We may suspend, modify, or discontinue the Service or any feature at any time, with or without notice. We are not liable for any loss or inconvenience arising from downtime or service changes.`,
  },
  {
    title: '9. Disclaimer of Warranties',
    body: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. WE EXPRESSLY DISCLAIM ALL WARRANTIES INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL MEET YOUR REQUIREMENTS OR THAT AI-GENERATED FEEDBACK WILL BE ACCURATE, COMPLETE, OR SUITABLE FOR ANY PURPOSE.`,
  },
  {
    title: '10. Limitation of Liability',
    body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE OPERATORS, THEIR AFFILIATES, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, ACADEMIC OPPORTUNITIES, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.\n\nIN ANY CASE, OUR TOTAL AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATING TO THE SERVICE SHALL NOT EXCEED THE TOTAL AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR USD $10, WHICHEVER IS GREATER. FREE-PLAN USERS ACKNOWLEDGE THAT THE SERVICE IS PROVIDED AT NO CHARGE AND THAT THIS LIMITATION IS REASONABLE GIVEN THE CIRCUMSTANCES.`,
  },
  {
    title: '11. Indemnification',
    body: `You agree to indemnify, defend, and hold harmless Critup.ai and the Operators from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable legal fees) arising from: (a) your use of the Service; (b) your violation of these Terms; (c) your uploaded content; or (d) your violation of any third-party rights.`,
  },
  {
    title: '12. Dispute Resolution',
    body: `You agree to contact us at hello@critup.ai and attempt to resolve any dispute informally before initiating formal proceedings. If informal resolution fails within 30 days, disputes shall be resolved by binding arbitration under the rules of the Dubai International Arbitration Centre (DIAC), conducted in English. You waive any right to participate in a class-action lawsuit or class-wide arbitration against Critup.ai.`,
  },
  {
    title: '13. Governing Law',
    body: `These Terms are governed by the laws of the United Arab Emirates and the Emirate of Dubai. To the extent that any matter is not covered by arbitration, you consent to the exclusive jurisdiction of the courts of Dubai, UAE.`,
  },
  {
    title: '14. Changes to These Terms',
    body: `We may update these Terms at any time. Material changes will be communicated by email at least 14 days before taking effect. Your continued use of the Service after the effective date constitutes acceptance of the revised Terms. If you do not agree, you must stop using the Service and cancel any active subscription before the effective date.`,
  },
  {
    title: '15. Miscellaneous',
    body: `If any provision of these Terms is found unenforceable, it will be modified to the minimum extent necessary to make it enforceable, with the remaining provisions continuing in full force. These Terms constitute the entire agreement between you and Critup.ai regarding the Service and supersede all prior agreements. Our failure to enforce any right does not constitute a waiver of that right.`,
  },
  {
    title: '16. Contact',
    body: `For questions about these Terms, email hello@critup.ai. Operator details: Critup.ai — Avraam Valikhan & Adil Kamal Batcha.`,
  },
]

export function TermsPage() {
  const { theme } = useTheme()
  const c = useColors(theme)

  return (
    <div style={{ background: c.bg, color: c.textPrimary, minHeight: '100vh', fontFamily: "'Inter', sans-serif" }}>
      <nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 48px', height: 60, borderBottom: `1px solid ${c.border}` }}>
        <Link to="/landing"><CritupLogo size={20} showText theme={theme} /></Link>
        <Link to="/landing" style={{ fontSize: 13, color: c.textMuted, textDecoration: 'none' }}>← Back</Link>
      </nav>

      <div style={{ maxWidth: 720, margin: '0 auto', padding: '64px 24px 80px' }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: '#F97316', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 12 }}>Legal</div>
        <h1 style={{ fontSize: 40, fontWeight: 800, letterSpacing: '-0.035em', margin: '0 0 8px', fontFamily: FONT }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: c.textMuted, margin: '0 0 8px' }}>Last updated: May 2026</p>
        <p style={{ fontSize: 13, color: c.textMuted, margin: '0 0 48px', lineHeight: 1.6, padding: '14px 16px', background: c.cardBg, borderRadius: 10, border: `1px solid ${c.border}` }}>
          Please read these Terms carefully before using Critup.ai. By accessing or using the Service you agree to be bound by these Terms. These Terms contain important limitations on our liability and a dispute resolution clause requiring arbitration.
        </p>

        {sections.map(({ title, body }) => (
          <div key={title} style={{ marginBottom: 40 }}>
            <h2 style={{ fontSize: 17, fontWeight: 700, letterSpacing: '-0.02em', margin: '0 0 12px', fontFamily: FONT, color: c.textPrimary }}>{title}</h2>
            {body.split('\n\n').map((para, i) => (
              <p key={i} style={{ fontSize: 14, color: c.textMuted, lineHeight: 1.75, margin: i < body.split('\n\n').length - 1 ? '0 0 12px' : '0' }}>{para}</p>
            ))}
          </div>
        ))}

        <div style={{ borderTop: `1px solid ${c.border}`, paddingTop: 32, fontSize: 13, color: c.textMuted }}>
          Questions? Email <a href="mailto:hello@critup.ai" style={{ color: '#F97316', textDecoration: 'none' }}>hello@critup.ai</a>
        </div>
      </div>
    </div>
  )
}
