import { Link } from '@tanstack/react-router'
import { CritupLogo } from '@/components/CritupLogo'
import { useTheme, useColors } from '@/lib/theme'

const FONT = "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Helvetica Neue', 'Inter', sans-serif"

export function TermsPage() {
  const { theme } = useTheme()
  const c = useColors(theme)

  return (
    <div style={{ background: c.bg, color: c.textPrimary, minHeight: '100vh', fontFamily: "'Inter', sans-serif" }}>
      <nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 48px', height: 60, borderBottom: `1px solid ${c.border}` }}>
        <Link to="/landing"><CritupLogo size={20} showText theme={theme} /></Link>
        <Link to="/landing" style={{ fontSize: 13, color: c.textMuted, textDecoration: 'none' }}>← Back</Link>
      </nav>

      <div style={{ maxWidth: 680, margin: '0 auto', padding: '64px 24px' }}>
        <div style={{ fontSize: 11, fontWeight: 700, color: '#F97316', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 12 }}>Legal</div>
        <h1 style={{ fontSize: 40, fontWeight: 800, letterSpacing: '-0.035em', margin: '0 0 8px', fontFamily: FONT }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: c.textMuted, margin: '0 0 48px' }}>Last updated: May 2026</p>

        {[
          {
            title: 'Who can use Critup.ai',
            body: `Critup.ai is available to anyone aged 16 or older. The platform is designed for architecture, interior design, and urban planning students, but is open to all design disciplines. By creating an account you confirm that the information you provide is accurate.`,
          },
          {
            title: 'What Critup.ai provides',
            body: `Critup.ai provides AI-generated design critique, jury question prediction, voice narration, and a coaching assistant ("Crit"). All feedback is generated by AI and is intended as educational guidance only. It does not constitute professional architectural advice and should not be used as a substitute for feedback from licensed professionals or faculty.`,
          },
          {
            title: 'Your content',
            body: `You retain full ownership of all project files and drawings you upload. By uploading, you grant Critup.ai a limited licence to process your files solely to provide the service. We do not claim any rights over your designs. You are responsible for ensuring you have the right to upload any files you submit.`,
          },
          {
            title: 'Acceptable use',
            body: `You may not use Critup.ai to submit content that infringes intellectual property rights, contains harmful or illegal material, or attempts to abuse or reverse-engineer the service. Automated bulk submissions and scraping are prohibited. Accounts found violating these terms may be suspended without notice.`,
          },
          {
            title: 'AI-generated content disclaimer',
            body: `Critup.ai uses large language models (Anthropic Claude) to generate critique and feedback. AI-generated content can be inaccurate, inconsistent, or biased. Scores may vary between submissions of the same work. Use the feedback as one input among many — not as a definitive assessment of your project's quality.`,
          },
          {
            title: 'Payments and refunds',
            body: `Paid subscriptions (Monthly and Yearly plans) are billed in advance. You may cancel at any time from Settings. Cancellation takes effect at the end of the current billing period — you retain access until then. We do not offer refunds for partial periods unless required by applicable law.`,
          },
          {
            title: 'Limitation of liability',
            body: `Critup.ai is provided "as is". We make no guarantees about uptime, accuracy of AI feedback, or fitness for any particular purpose. To the maximum extent permitted by law, Critup.ai is not liable for any indirect, incidental, or consequential damages arising from use of the service.`,
          },
          {
            title: 'Changes to these terms',
            body: `We may update these terms from time to time. Significant changes will be communicated by email. Continued use of the service after changes take effect constitutes acceptance of the updated terms.`,
          },
          {
            title: 'Contact',
            body: `For questions about these terms, email legal@critup.ai.`,
          },
        ].map(({ title, body }) => (
          <div key={title} style={{ marginBottom: 40 }}>
            <h2 style={{ fontSize: 18, fontWeight: 700, letterSpacing: '-0.02em', margin: '0 0 12px', fontFamily: FONT, color: c.textPrimary }}>{title}</h2>
            <p style={{ fontSize: 14, color: c.textMuted, lineHeight: 1.75, margin: 0 }}>{body}</p>
          </div>
        ))}

        <div style={{ borderTop: `1px solid ${c.border}`, paddingTop: 32, fontSize: 13, color: c.textMuted }}>
          Questions? Email <a href="mailto:legal@critup.ai" style={{ color: '#F97316', textDecoration: 'none' }}>legal@critup.ai</a>
        </div>
      </div>
    </div>
  )
}
